package com.digital.common.enums;

public enum ErrorCode {
    VALIDATION_ERROR,
    INTERNAL_SERVER_ERROR,
    RESOURCE_NOT_FOUND,
    MALFORMED_JSON,
    ACCESS_DENIED,
    INVALID_CREDENTIALS,
    CUSTOMER_MOBILE_NUMBER_EXIST,
    CUSTOMER_ORDER_NOT_FOUND,
    CUSTOMER_NOT_FOUND,
    MERCHANT_NOT_FOUND,
    LOCATION_NOT_FOUND,
    MERCHANT_LOCATION_NOT_EXIST,
    MERCHANT_LOCATION_MENU_ITEM_NOT_EXIST,
    MERCHANT_FEIGN_CLIENT_ERROR
}
